import { Route, Location, RouteConfig, Dictionary } from '../type';
import { routeNotNested } from '../autoGeneratedConfig';
import { NAME_SPLITTER } from '../config';

export function createRoute(location: Location): Route {
    const route: Route = {
        name: location.name,
        path: location.path || '/',
        query: location.query || {},
    };
    return Object.freeze(route);
}

export const START: Route = createRoute({
    path: '/',
});

export function getNotNestedRoutes(): RouteConfig[] {
    return routeNotNested;
}
